GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/60042fe127e6be4b90d23944

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Minato Namikaze",
    "subscriberToChannel": "Hokage"
}

###

DELETE http://localhost:3000/subscribers/60042fe127e6be4b90d23944

###
PATCH http://localhost:3000/subscribers/60042fe127e6be4b90d23944
Content-Type: application/json

{
    "subscriberToChannel": "Yondaime Hokage"
}